### ISSUE TITLE
DOI not found

### ISSUE THREAD

**Issue by RuyiLian** [zhonge/cryodrgn_empiar#1]
Hi Ellen,

Thanks for sharing the data! I want to check the experiment outputs, and I see in README you write

> The outputs of the experiments (trained models and reconstructed volumes), which are too large to put in a github repository, can be found on zenodo.

However, when I clicked the link of zenodo, I received the message "DOI not found". Could you please check it again? Thank you!

**Comment by zhonge** [comment]
The DOI is reserved but I am still in the process of uploading them to zenodo (it is very slow and glitchy so I've had to change strategies a number of times...). I will update once it is available.

**Comment by RuyiLian** [comment]
Great, thanks!
